using Einzel.Core.Model;
using Einzel.Project;

namespace Einzel.Commands;

/// <summary>
/// Generates the platform layer of a project's AGENTS.md.
/// </summary>
/// <remarks>
/// <para>
/// AGD-1: <c>einzel init</c> writes an AGENTS.md containing two layers — how to
/// use Einzel, and how to work on this instrument — the first generated and
/// clearly delimited.
/// </para>
/// <para>
/// Generated, never hand-written, and the spec is blunt about why: "Instructions
/// shipped with v1.2 that describe v1.0 behaviour are worse than none, because an
/// agent trusts them and cannot detect the drift." The version stamp below is
/// what <c>einzel doctor</c> compares against, and UPD-7 regenerates this layer
/// when an update is applied.
/// </para>
/// </remarks>
public static class AgentsFile
{
    /// <summary>The marker that opens the generated region.</summary>
    public const string BeginMarker = "<!-- BEGIN GENERATED: einzel platform guidance -->";

    /// <summary>The marker that closes the generated region.</summary>
    public const string EndMarker = "<!-- END GENERATED -->";

    private const string VersionMarker = "Generated by einzel ";

    /// <summary>Generates a complete AGENTS.md, generated layer first.</summary>
    /// <returns>The file contents.</returns>
    public static string Generate()
    {
        var version = EngineBuild.Version;
        var schema = ModelSchema.CurrentVersion;
        var scratch = ProjectLayout.ScratchDirectoryName;

        // Two dollar signs, so a single brace is literal content and only {{...}}
        // interpolates. The document is mostly JSON examples, and escaping every
        // one of their braces would make this template unreadable.
        return $$"""
        # Agent guidance

        {{BeginMarker}}
        <!-- {{VersionMarker}}{{version}}. Do not edit this region by hand: it is
             regenerated by `einzel agents-md` and when the engine is updated, and
             hand edits will be lost. Guidance written for one engine version and
             left in place for another is worse than none, because it reads as
             authoritative and the drift is invisible. -->

        ## Platform, einzel {{version}} (model schema {{schema}})

        A project is a directory. Everything defining a modelling effort is a file
        under this root, and every operation is a command run against it. Read
        files, edit files, run commands, read output — there is no session and no
        protocol to hold open.

        ### Layout

        | Path | Contents |
        | --- | --- |
        | `models/` | model documents, JSON |
        | `studies/` | sweep and optimisation configurations |
        | `figures/` | render specifications, and the figures they produce |
        | `results/` | run manifests and figures of merit |
        | `tests/` | assertions on expected performance |
        | `extensions/` | Python extensions |
        | `{{scratch}}/` | caches and trajectories. Large, regenerable, safe to delete |

        ### The loop

        ```
        einzel validate models/<name>.json     # instant; units, bounds, regime validity
        einzel run models/<name>.json          # writes results/<name>.result.json
        einzel run models/<name>.json --vtu    # also writes a trajectory for ParaView
        ```

        Add `--json` to any command for machine-readable output. Results go to
        stdout, diagnostics to stderr. Exit codes are distinct per failure class:
        0 success, 1 validation failure, 2 regime violation, 3 cost-gate refusal,
        4 convergence failure, 5 engine-pin mismatch, 6 internal error.

        ### Rules worth knowing before editing a model

        - **Every quantity carries a unit.** `{"value": 4, "unit": "kV"}`, never
          `4000`. A bare number is a validation error, deliberately. Unit symbols
          are case-sensitive: `mm` and `Mm` differ by nine orders of magnitude.
        - **No result is ever a bare number.** Every value arrives with its
          uncertainty, the evidence behind it, and any warnings. If a flight time
          comes back with a warning attached, that warning is part of the answer.
        - **Warnings above advisory cannot be suppressed**, by any caller, in any
          mode. When one appears the fix belongs in the model, not the invocation.
        - **Errors are recovery instructions.** Each names the offending path, the
          constraint violated, what was observed, and a suggested correction. Act
          on what it names rather than guessing.

        ### Reading a validation failure

        ```json
        {
          "code": "UNITS_INCOMPATIBLE",
          "path": "/source/accelerationPotential",
          "constraint": "this field requires a quantity of dimension m^2 kg s^-3 A^-1",
          "observed": { "value": 4, "unit": "mm" },
          "suggestion": "'mm' has dimension m; supply a unit of dimension m^2 kg s^-3 A^-1"
        }
        ```

        `path` is a JSON Pointer into the model document. Edit that location.

        {{EndMarker}}

        ## This instrument

        <!-- Yours. What is being built, what has been tried, what the targets are,
             and anything an agent should know that the model files do not say.
             Nothing below the marker above is ever regenerated. -->

        Describe the instrument here.

        """;
    }

    /// <summary>Reads the engine version recorded in an existing AGENTS.md.</summary>
    /// <param name="contents">The file contents.</param>
    /// <returns>The recorded version, or null when absent.</returns>
    /// <remarks>
    /// What <c>einzel doctor</c> compares against the running build to report that
    /// a project's guidance has fallen behind the installed engine.
    /// </remarks>
    public static string? RecordedVersion(string contents)
    {
        if (string.IsNullOrEmpty(contents))
        {
            return null;
        }

        var start = contents.IndexOf(VersionMarker, StringComparison.Ordinal);

        if (start < 0)
        {
            return null;
        }

        start += VersionMarker.Length;
        var end = start;

        // Version strings contain dots and dashes, so scan to the first character
        // that cannot be part of one, then drop a trailing sentence period.
        while (end < contents.Length
            && (char.IsLetterOrDigit(contents[end]) || contents[end] is '.' or '-' or '+'))
        {
            end++;
        }

        var version = contents[start..end].TrimEnd('.');
        return string.IsNullOrWhiteSpace(version) ? null : version;
    }
}
